# docker-compose.yml

version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USE`: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - '5432:5432'
    volumes:
      - devicemanager-db:/var/lib/postgresql/data

  devicemanager:
    build:
      context: .
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - '3000:3000'
        
volumes:
  devicemanager-db:
